---
- name: RASI backend provisioning
  hosts: rasi_web_servers
  tasks:
    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
        upgrade: yes
      become: yes

    - name: Clone RASI monorepo
      git:
        repo: https://github.com/Ctrl-AltDefeat/RASI.git
        update: yes

- name: RASI db provisioning
  hosts: rasi_db
  tasks:
    - name: Install postgresql
      apt:
        name:
          - postgresql
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
        upgrade: yes
