---
version: "3.8"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    user: dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: biproyect
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bi.com
      PGADMIN_DEFAULT_PASSWORD: admin
    network_mode: service:postgres
    depends_on:
      - postgres

volumes:
  postgres-data: